version: '3'
services:
  ruoyi_db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ruoyi_db_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d
  ruoyi_redis:
    image: redis:alpine
    ports:
      - 6379:6379

  ruoyi-be:
    # restart: unless-stopped
    build:
      context: .
      dockerfile: be.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ruoyi_be_logs:/logs
    depends_on:
      - ruoyi_db
      - ruoyi_redis
        
  ruoyi_fe:
    restart: unless-stopped
    build:
      context: .
      dockerfile: fe.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ruoyi-be
    
volumes:
  ruoyi_be_logs: 
  ruoyi_db_data: 
